# Generated by Django 4.2.2 on 2023-07-08 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idProducto', models.ManyToManyField(to='Productos.producto', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'Cuidad',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField()),
                ('idCarrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.carrito', verbose_name='Carrito')),
                ('idDescuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.descuentos', verbose_name='Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Medico')),
            ],
            options={
                'verbose_name': 'Consulta ',
                'verbose_name_plural': 'Consultas',
                'db_table': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='FormadePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formadepago', models.CharField(choices=[('PSE', 'PSE'), ('TC', 'Tarjeta Credito'), ('TD', 'Tarjeta Debito')], max_length=10, verbose_name='Forma de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('idCompra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra', verbose_name='Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcciondeEntrega', models.CharField(max_length=100)),
                ('idCiudad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Compra.ciudad', verbose_name='Ciudad')),
                ('idUsuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('idConsulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.consulta', verbose_name='Consulta')),
                ('idProducto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto', verbose_name='Producto')),
                ('idUsuario', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='idDetalleConsulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Compra.detalleconsulta', verbose_name='Detalle Consulta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idDomicilio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Compra.domicilio', verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idFormadePago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.formadepago', verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='idDepartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.departamento', verbose_name='Departamento'),
        ),
    ]
